const tours: any[] = [
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 1,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: true
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 1,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: false
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 4,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: false
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 4,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: true
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 3,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: true
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 3,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: false
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 2,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 12.00,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: true
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 2,
    temperatur: [{
      currentDegreeVehicle: 11.65,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 12.00,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: false
  },
  {
    tourId: 99000000000566,
    tourNr: "2070",
    tourPlaceTime: null,
    tourStartTime: null,
    tourStartTimeInMinute: null,
    tourPlaceTimeInMinute: null,
    presortCountTotal: "0 + 0",
    presortCountCurrent: 0,
    presortCountCurrentPercent: 0,
    presortStatus: "",
    loadingCountTotal: "0 + 0",
    loadingCountCurrent: 0,
    loadingCountCurrentPercent: 0,
    loadingStatus: "rgb(249, 66, 12)",
    cashReturn: 0,
    cashReturnStatus: "rgb(218, 218, 218)",
    driverRegistration: false,
    driverName: null,
    driverRegistrationStatus: "rgb(249, 66, 12)",
    rearrangeCount: 0,
    rearrangeTours: ['VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', 'VL', '003', '003', 'DZ', 'DZ', 'DZ', 'DZ'],
    rearrangerStatus: "rgb(218, 218, 218)",
    requestDriverSupporter: null,
    requestDriverSupporterStatus: null,
    tourStatus: "rgb(249, 66, 12)",
    tourStatusSort: 4,
    temperatur: [{
      currentDegreeVehicle: 11.22,
      degreeeStatus: "rgb(218, 218, 218)",
    },
    {
      currentDegreeVehicle: 11.22,
      degreeeStatus: "rgb(218, 218, 218)",
    }],
    labelingObligation: false
  },

];

export default tours;

export enum TourType{
  RED = 1,
  YELLOW = 2,
  GREEN = 3,
  GRAY = 4
}

export enum TourSektorName{
  RED = 'Kritisch',
  YELLOW = 'Zu Prüfen',
  GREEN = 'In Ordnung',
  GRAY = 'Abgefertigte Touren'
}

